
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Apr 05 15:59:00 EDT 2013
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class A4Symbol {
  /* terminals */
  public static final int TIMES = 18;
  public static final int READ = 5;
  public static final int ELSE = 3;
  public static final int PLUS = 16;
  public static final int RPAREN = 15;
  public static final int INT = 10;
  public static final int SEMI = 12;
  public static final int IDENTIFIER = 24;
  public static final int END = 8;
  public static final int RETURN = 6;
  public static final int ERROR = 23;
  public static final int IF = 2;
  public static final int LPAREN = 14;
  public static final int WRITE = 4;
  public static final int QUOTE = 26;
  public static final int BEGIN = 7;
  public static final int COMMA = 13;
  public static final int NUMBER = 25;
  public static final int NEQUAL = 22;
  public static final int EOF = 0;
  public static final int DIVIDE = 19;
  public static final int MAIN = 9;
  public static final int MINUS = 17;
  public static final int CEQUAL = 20;
  public static final int error = 1;
  public static final int REAL = 11;
  public static final int EEQUAL = 21;
}

