
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Mar 15 10:38:13 EDT 2013
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class A3Symbols {
  /* terminals */
  public static final int TIMES = 20;
  public static final int READ = 7;
  public static final int ELSE = 5;
  public static final int PLUS = 18;
  public static final int RPAREN = 17;
  public static final int INT = 12;
  public static final int SEMI = 14;
  public static final int END = 10;
  public static final int RETURN = 8;
  public static final int IDENTIFIER = 3;
  public static final int IF = 4;
  public static final int LPAREN = 16;
  public static final int WRITE = 6;
  public static final int BEGIN = 9;
  public static final int QUOTE = 2;
  public static final int COMMA = 15;
  public static final int NUMBER = 25;
  public static final int NEQUAL = 24;
  public static final int EOF = 0;
  public static final int DIVIDE = 21;
  public static final int MAIN = 11;
  public static final int MINUS = 19;
  public static final int CEQUAL = 22;
  public static final int error = 1;
  public static final int REAL = 13;
  public static final int EEQUAL = 23;
}

