#!/bin/bash

#echo Welcome to C-shell scripting
#myfirstvar=hello
#echo $myfirstvar
#myfirstvar=there
#echo $myfirstvar
echo "Today is "`date +"%A, %B %d"`
#echo The program name is: $0
#echo The first argument is: $1
#echo The second argument is: $argv[2]
#echo The second argument is also: $2
#echo All the arguments are: $*
#echo The total number of arguments is: $#argv
